--query 1 (list all patients)

SELECT SUBJECT_ID, DOB, GENDER
FROM PATIENTS;

--query 2 (admissions of a given patient)
SELECT * FROM ADMISSIONS
WHERE SUBJECT_ID = SELECT * FROM ADMISSIONS
WHERE SUBJECT_ID = 3288;  -- sample id
;  

--query 3 (number of admissions for a given patient)
SELECT SUBJECT_ID, COUNT(HADM_ID) AS NUM_ADMISSIONS
FROM ADMISSIONS
GROUP BY SUBJECT_ID;

--query 4 (all patients that were discharged to home)
SELECT DISTINCT SUBJECT_ID
FROM ADMISSIONS
WHERE DISCHARGE_LOCAITON = 'HOME';
--query 5 (patients with private insurance)
SELECT DISTINCT p.SUBJECT_ID, p.DOB, p.GENDER, a.INSURANCE
FROM PATIENTS p 
JOIN ADMISSIONS a 
    ON p.SUBJECT_ID = a.SUBJECT_ID
WHERE a.INSURANCE = 'Private';

--query 6 (patients transferred from one location to another location)
SELECT DISTINCT p.SUBJECT_ID, i.FIRST_CAREUNIT, i.LAST_CAREUNIT, i.FIRST_WARDID, i.LAST_CAREUNIT
FROM PATIENTS p
JOIN ICUSTAYS i 
    ON p.SUBJECT_ID = i.SUBJECT_ID
WHERE i.FIRST_CAREUNIT <> i.LAST_CAREUNIT
   OR i.FIRST_WARDID <> i.LAST_WARDID;

--query 7 (patients who have > 1 ICU stays in a single hodpital admission)
SELECT SUBJECT_ID, HADM_ID, COUNT(ICUSTAY_ID) AS TOTAL_ICU_STAYS
FROM ICUSTAYS 
GROUP BY SUBJECT_ID, HADM_ID
HAVING COUNT(ICUSTAY_ID) > 1;

--query 8 (patients in the ICU admitted to MICU until they left)
SELECT DISTINCT p.SUBJECT_ID, i.ICUSTAY_ID, i.FIRST_CAREUNIT, i.LAST_CAREUNIT
FROM PATIENTS p 
JOIN ICUSTAYS i 
    ON p.SUBJECT_ID = i.SUBJECT_ID
WHERE i.FIRST_CAREUNIT = 'MICU'
  AND i.LAST_CAREUNIT = 'MICU';

-- query 9 (all notes for a specific admission ID with its author and error if any)
SELECT HADM_ID, SUBJECT_ID, E_DESCRIPTION, E_TEXT, CATEGORY, CGID, ISERROR
FROM NOTEEVENTS 
WHERE HADM_ID = '5002' --sample hospital admission id
-- query 10
SELECT *
FROM NOTEEVENTS
WHERE CATEGORY = 'Discharge summary'
ORDER BY CHARTTIME
LIMIT 10;

-- query 11
SELECT HADM_ID, COUNT(*) AS num_notes
FROM NOTEEVENTS
GROUP BY HADM_ID;

-- query 12 can replace the subject_id with anyone (a given patient)
SELECT d.ICD9_CODE, d.SHORT_TITLE, d.LONG_TITLE
FROM DIAGNOSES_ICD di
JOIN D_ICD_DIAGNOSES d ON di.ICD9_CODE = d.ICD9_CODE
WHERE di.SUBJECT_ID = 101;

-- query 13
SELECT d.ICD9_CODE, d.LONG_TITLE, COUNT(*) AS frequency
FROM DIAGNOSES_ICD di
JOIN D_ICD_DIAGNOSES d ON di.ICD9_CODE = d.ICD9_CODE
GROUP BY d.ICD9_CODE, d.LONG_TITLE
ORDER BY frequency DESC
LIMIT 5;

-- query 14
SELECT DISTINCT a.*
FROM ADMISSIONS a
JOIN ICUSTAYS i ON a.HADM_ID = i.HADM_ID
JOIN DIAGNOSES_ICD di ON a.HADM_ID = di.HADM_ID
WHERE di.ICD9_CODE = '401.9';

-- query 15
SELECT SUBJECT_ID FROM PATIENTS 
WHERE SUBJECT_ID NOT IN (SELECT DISTINCT SUBJECT_ID FROM ICUSTAYS);

-- query 16
SLECT DISTINCT p.SUBJECT_ID, p.GENDER, p.DOB FROM PATIENTS
p INNER JOIN NOTEEVENTS n ON p.SUBJECT_ID WHERE n.CATEGORY = 'Radiology';

-- query 17
SELECT DISTINCT p.SUBJECT_ID, p.GENDER, p.DOB FROM PATIENTS p 
INNER JOIN NOTEEVENTS n ON p.SUBJECT_ID = n.SUBJECT_ID WHERE n.CATEGORY = 'Radiology' AND
(n.E_DESCRIPTION LIKE '%CHEST%' OR n.E_TEXT LIKE '%chest$');

-- query 18
SLECT DISTINCT p.SUBJECT_ID, p.GENDER, p.DOB FROM PATIENTS
p INNER JOIN NOTEEVENTS n ON p.SUBJECT_ID = n. n.SUBJECT_ID WHERE n.CATEGORY = 'Discharge summary';

-- query 19  
SELECT DISTINCT p.SUBJECT_ID, p.GENDER, p.DOB, n.CATEGORY
FROM PATIENTS
p INNER JOIN NOTEEVENTS n ON p.SUBJECT_ID = n.SUBJECT_ID 
WHERE n.CATEGORY IN ('Radiology', 'ECG') ORDER BY p.SUBJECT_ID, n.CATEGORY;

-- query 20 
SELECT
    (SELECT COUNT(HADM_ID) FROM ADMISSIONS WHERE SUBJECT_ID = 26) AS Total_Admissions,
    (SELECT COUNT(ICUSTAY_ID) FROM ICUSTAYS WHERE SUBJECT_ID = 26) AS Total_Icu_Stays,
    (SELECT COUNT(ICD9_CODE) FROM DIAGNOSES_ICD WHERE SUBJECT_ID = 26) AS Total_Diagnoses;