DROP  DATABASE hsp_db;

CREATE DATABASE HSP_DB;
USE HSP_DB;

CREATE TABLE PATIENTS(
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT PRIMARY KEY,
    GENDER VARCHAR(5) NOT NULL,
    DOB DATETIME  NOT NULL,
    DOD DATETIME  NULL,
    DOD_HOSP DATETIME  NULL,
    DOD_SSN DATETIME  NULL,
    EXPIRE_FLAG VARCHAR(5) NULL
);

CREATE TABLE ADMISSIONS(
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL, -- Foreign Key
    HADM_ID INT PRIMARY KEY,
    ADMITTIME DATETIME  NOT NULL,
    DISCHTIME DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    DEATHIME DATETIME  NULL,
    ADMISSION_TYPE VARCHAR(50) NOT NULL,
    ADMISSION_LOCATION VARCHAR(50) NOT NULL,
    DISCHARGE_LOCAITON VARCHAR(50) NOT NULL,
    INSURANCE VARCHAR(255) NULL,
    LANG VARCHAR(10) NOT NULL,
    RELIGION VARCHAR(50) NULL,
    MARITAL_STATUS VARCHAR(50) NULL,
    ETHNICITY VARCHAR(200) NULL,
    EDREGTIME DATETIME  NULL,
    EDOUTTIME DATETIME  NULL,
    DIAGNOSIS VARCHAR(300) NOT NULL,
    HOSPITAL_EXPIRE_FLAG TINYINT NOT NULL DEFAULT 0,
    HAS_CHARTEVENTS_DATA TINYINT NOT NULL,
    CONSTRAINT fk_admissions_patients
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID)
);

CREATE TABLE NOTEEVENTS(
    ROW_ID INT PRIMARY KEY,
    SUBJECT_ID INT NOT NULL, -- Foreign key
    HADM_ID INT NOT NULL, -- Foreign key
    CHARDATE DATETIME  NOT NULL,
    CHARTTIME DATETIME  NULL,
    STORETIME DATETIME  NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    E_DESCRIPTION VARCHAR(300) NOT NULL, -- E_ for EVENTS
    CGID INT NOT NULL,
    ISERROR CHAR(1) NULL,
    E_TEXT MEDIUMTEXT NOT NULL,
    CONSTRAINT fk_noteevent_patients
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID),
    CONSTRAINT fk_noteevents_admissions
    FOREIGN KEY (HADM_ID) REFERENCES ADMISSIONS(HADM_ID)
);

CREATE TABLE D_ICD_DIAGNOSES(
    ROW_ID INT NOT NULL, 
    ICD9_CODE VARCHAR(10) PRIMARY KEY,
    SHORT_TITLE VARCHAR(10) NOT NULL,
    LONG_TITLE VARCHAR(300) NOT NULL
);

CREATE TABLE DIAGNOSES_ICD(
    ROW_ID INT PRIMARY KEY,
    SUBJECT_ID INT NOT NULL, -- Foreign key
    HADM_ID INT NOT NULL, -- Foreign Key
    SEQ_NUM INT NULL,
    ICD9_CODE VARCHAR(10) NOT NULL,-- Foreign Key
    CONSTRAINT fk_diagnosesicd_patients
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID),
    CONSTRAINT fk_diagnosesicd_admissions
    FOREIGN KEY (HADM_ID) REFERENCES ADMISSIONS(HADM_ID),
    CONSTRAINT fk_diagnosesicd_dicddiagnoses
    FOREIGN KEY (ICD9_CODE) REFERENCES D_ICD_DIAGNOSES(ICD9_CODE)
);

CREATE TABLE ICUSTAYS(
    ROW_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    HADM_ID INT NOT NULL,
    ICUSTAY_ID INT PRIMARY KEY,
    DBSOURCE VARCHAR(20) NOT NULL,
    FIRST_CAREUNIT VARCHAR(20) NOT NULL,
    LAST_CAREUNIT VARCHAR(20) NOT NULL,
    FIRST_WARDID SMALLINT NOT NULL,
    LAST_WARDID SMALLINT NOT NULL,
    INTIME DATETIME NOT NULL,
    OUTTIME DATETIME  NULL,
    LOS DOUBLE PRECISION NULL
    
);

